#!/usr/bin/php
<?php
if(sizeof($argv) < 2){
  echo "\n";
  echo "Description: Generates 254 ip addresses from specified prefix\n";
  echo "Usage: ./ipgen ip_addr_prefix\n";
  echo "Example: ./ipgen 10.99.4\n";
  echo "Result: this will generate 254 addresses from 10.99.4.0/24\n";
  echo "Warning: do not reuse a prefix to avoid duplicate addresses\n";
  echo "\n";
  exit();
}

$conf = include('config.php');
$prefix = $argv[1];
$file=file_get_contents($conf->ip_addr_file);
$ips = json_decode($file,true);

for($i=1;$i < 254; $i++){
  $ips[] = array ('ip' => $prefix . "." . $i, 'used' => false);
}
$json = json_encode($ips);
file_put_contents($conf->ip_addr_file,$json);

